### PR TITLE
Remove gosu

### PR DESCRIPTION
**Pull request by kiasaki**

### CODE REVIEW

**Comment by kiasaki** [comment]
@kalitad Could you show me how your modified docker entrypoint looks like, removing `gosu` is causing some permission problems with the entrypoints commands... Might also be the mounted volume.

```
docker run -i -P alpine-postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
sed: /var/lib/postgresql/data/postgresql.conf: No such file or directory
...
```

**Comment by kalitad** [comment]
Hi @kiasaki , check attached files. For me it's working.

[docker-entrypoint.TXT](https://github.com/kiasaki/docker-alpine-postgres/files/117819/docker-entrypoint.TXT)
[Dockerfile.TXT](https://github.com/kiasaki/docker-alpine-postgres/files/117820/Dockerfile.TXT)

**Comment by kiasaki** [comment]
Ah, I see, this `Dockerfile` uses the `VOLUME` instruction and `chown`ing the PGDATA dir in the `Dockerfile` doesn't seem to do the trick, I need to do it in the `docker-entrypoint.sh` (where it is done ATM using `gosu`)

You get away with it by having the data reside in the container using: `RUN mkdir -p $PGDATA && \chown -R postgres $PGDATA`. I am guessing most people will prefer a folder to be mounted so that their data persists after the container gets killed.

**Comment by Recmo** [comment]
Just a note, you no longer have to install and remove `curl`, further simplifying the `Dockerfile`.

**Comment by kiasaki** [comment]
Thanks @Remco is that new in Alpine Linux version 3.3 or is it only added in the "official" `alpine:3.3` docker image.

We are using `gliderlabs/alpine:3.3` as a base image in this repo, does it still apply?

**Comment by Recmo** [comment]
It has little to do with the base image. In the original `Dockerfile` the package `curl` was installed, then `curl` was used to download `gosu` and then `curl` was removed again. Since this patch removes the only use of `curl`, there is no need to install and remove it.

Like this [commit](https://github.com/Recmo/docker-alpine-postgres/commit/1a608bfbf96dfded14812b9cbd85f7c71e637ead).

**Comment by kiasaki** [comment]
Ha, sorry totally misunderstood the comment. Indeed, curl is not needed anymore where we used to fetch gosu

**Comment by robbyoconnor** [comment]
Why remove gosu?

**Comment by kiasaki** [comment]
Mostly one less dependency / install steps.

But at this point it would just be a disservice as to support uses cases where you mount volume we need to call `chmod` using `gosu` from in `docker-entrypoint.sh`.

**Pull request closed without merging**
